"""baseline

Revision ID: 126256544b67
Revises: 
Create Date: 2026-02-25 00:56:16.697406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126256544b67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SUBJECTS',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(op.f('ix_SUBJECTS_subject_id'), 'SUBJECTS', ['subject_id'], unique=False)
    op.create_table('USERS',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_USERS_user_id'), 'USERS', ['user_id'], unique=False)
    op.create_table('SESSIONS',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('audio_file_name', sa.String(), nullable=True),
    sa.Column('transcript_source', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['SUBJECTS.subject_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['USERS.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_SESSIONS_session_id'), 'SESSIONS', ['session_id'], unique=False)
    op.create_index(op.f('ix_SESSIONS_youtube_url'), 'SESSIONS', ['youtube_url'], unique=True)
    op.create_table('TRANSCRIPTS',
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['SESSIONS.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transcript_id')
    )
    op.create_index(op.f('ix_TRANSCRIPTS_session_id'), 'TRANSCRIPTS', ['session_id'], unique=True)
    op.create_index(op.f('ix_TRANSCRIPTS_transcript_id'), 'TRANSCRIPTS', ['transcript_id'], unique=False)
    op.create_table('TRANSCRIPT_CHUNKS',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['SESSIONS.session_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['SUBJECTS.subject_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_TRANSCRIPT_CHUNKS_chunk_id'), 'TRANSCRIPT_CHUNKS', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_TRANSCRIPT_CHUNKS_session_id'), 'TRANSCRIPT_CHUNKS', ['session_id'], unique=False)
    op.create_index(op.f('ix_TRANSCRIPT_CHUNKS_subject_id'), 'TRANSCRIPT_CHUNKS', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TRANSCRIPT_CHUNKS_subject_id'), table_name='TRANSCRIPT_CHUNKS')
    op.drop_index(op.f('ix_TRANSCRIPT_CHUNKS_session_id'), table_name='TRANSCRIPT_CHUNKS')
    op.drop_index(op.f('ix_TRANSCRIPT_CHUNKS_chunk_id'), table_name='TRANSCRIPT_CHUNKS')
    op.drop_table('TRANSCRIPT_CHUNKS')
    op.drop_index(op.f('ix_TRANSCRIPTS_transcript_id'), table_name='TRANSCRIPTS')
    op.drop_index(op.f('ix_TRANSCRIPTS_session_id'), table_name='TRANSCRIPTS')
    op.drop_table('TRANSCRIPTS')
    op.drop_index(op.f('ix_SESSIONS_youtube_url'), table_name='SESSIONS')
    op.drop_index(op.f('ix_SESSIONS_session_id'), table_name='SESSIONS')
    op.drop_table('SESSIONS')
    op.drop_index(op.f('ix_USERS_user_id'), table_name='USERS')
    op.drop_table('USERS')
    op.drop_index(op.f('ix_SUBJECTS_subject_id'), table_name='SUBJECTS')
    op.drop_table('SUBJECTS')
    # ### end Alembic commands ###
