"""audit_fixes

Revision ID: 477e454335de
Revises: 126256544b67
Create Date: 2026-02-25 01:59:26.783324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477e454335de'
down_revision: Union[str, Sequence[str], None] = '126256544b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SESSIONS', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('SESSIONS', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('SESSIONS', sa.Column('failure_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SESSIONS', 'failure_reason')
    op.drop_column('SESSIONS', 'completed_at')
    op.drop_column('SESSIONS', 'started_at')
    # ### end Alembic commands ###
